TOTAL_OBJECTS: 8
SEED: 0
AGENT:
  hover_steps: 1000
  MAPS:
    map_size: 880
    feature_map_channels: 3
    occupancy_map_channels: 1
    coordinate_min: -44.0
    coordinate_max:  44.0
    affinity_measure: "binary_image_detect"
    goal_measure: "threshold"
    goal_threshold: 0.8
    egocentric_map_size: 100
    depth_march_size: 0.3
  VISUALIZE:
    target: ["rgb", "depth", "frontier_map", "occupancy_map"]
  PLANNING:
    waypoint_thres: 0.16
    min_waypoint_spacing: 3
    collision_thres: 0.03
    angle_th: 0.349
    collision_protocol: 'turn'
    collision_fill_in: 'None'
    collision_random_steps: 3
    consider_tgt: ["collision"]
    hole_thres: 0.2
    max_pseudo_goal_step: 10
